CREATE TABLE services (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          title VARCHAR(100) NOT NULL,
                          description TEXT,
                          price NUMERIC(15, 2) NOT NULL,
                          owner_user_id BIGINT NOT NULL,
                          created_at TIMESTAMP(6),
                          updated_at TIMESTAMP(6)
)